measurements-group:
  name: "g"
  
  image-files:
    path: "simnb01_g_01.fits"

  aperture-photometry:
    size: 5

measurements-group:
  name: "r"
  
  image-files:
    path: "simnb01_r_01.fits"

  aperture-photometry:
    size:
      - 1
      - 2
      - 3
