#!/bin/bash
#
# File: scripts/AppRun
# Created on: 01/21/19
# Author: aalvarez
#
# Copyright (C) 2012-2020 Euclid Science Ground Segment
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3.0 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#

# Entry point for the AppImage
# We need to properly set up the PYTHONPATH so the SourceXtractor++ modules can be found
# within the image

export PATH="${APPDIR}/usr/bin:${PATH}"

if [ -f "${APPDIR}/usr/bin/python3" ]; then
    PYTHON_VERSION=$(python3 -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))")
else
    PYTHON_VERSION=$(python2 -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))")
fi

LIB="${APPDIR}/usr/lib"
LIB64="${APPDIR}/usr/lib64"

PYTHON_LIB="${LIB}/python${PYTHON_VERSION}"
PYTHON64_LIB="${LIB64}/python${PYTHON_VERSION}"

export PYTHONHOME="${PYTHON64_LIB}"
export PYTHONPATH="${PYTHON_LIB}:${PYTHON_LIB}/site-packages:${PYTHON64_LIB}:${PYTHON64_LIB}/site-packages:${PYTHON64_LIB}/lib-dynload/"
export LD_LIBRARY_PATH="${LIB64}:${LIB}:${LIB64}/atlas:${LD_LIBRARY_PATH}"

exec -a "${ARGV0}" "${APPDIR}/usr/bin/sourcextractor++" $@

