#!/bin/bash
#
# File: scripts/AppRun
# Created on: 01/21/19
# Author: aalvarez
#
# Copyright (C) 2012-2020 Euclid Science Ground Segment
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3.0 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#

# Entry point for the AppImage
# We need to properly set up the PYTHONPATH so the sextractor++ modules can be found
# within the image

export PATH="${APPDIR}/usr/bin:${PATH}"

if [ -f "${APPDIR}/usr/bin/python3" ]; then
    PYTHON_VERSION=$(python3 -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))")
else
    PYTHON_VERSION=$(python -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))")
fi

PYTHON_LIBS="${APPDIR}/usr/lib64/python${PYTHON_VERSION}/"

export PYTHONPATH="${PYTHON_LIBS}:${PYTHON_LIBS}/site-packages"
exec -a "${ARGV0}" "${APPDIR}/usr/bin/sextractor++" $@

