name: doc

on:
  push:
    paths:
      - 'doc/**'
  pull_request:
    paths:
      - 'doc/**'

jobs:

#############
# Build doc #
#############
  build:
    name: Make HTML doc
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r doc/requirements.txt

      - name: Build
        run: |
          cd doc
          make html
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: doc-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html/
          if: ${{ github.ref_name != 'master' }}
          destination_dir: ${{ github.ref_name }}

