name: RPM - Repository

on:
  push:
    branches: [ master, develop ]
    tags: [ '*' ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:

#######################
# Get Fedora Releases #
#######################
  get_fedora_releases:
    name: Get Fedora Releases
    runs-on: ubuntu-latest
    steps:
      - name: Query Fedora
        id: releases
        uses: sgallagher/get-fedora-releases-action@v1
    outputs:
      stable: ${{ steps.releases.outputs.stable }}
      development: ${{ steps.releases.outputs.development }}
      active: ${{ steps.releases.outputs.active }}

#############
# Build RPM #
#############
  build:
    name: Build (Active)
    needs: get_fedora_releases
    continue-on-error: false
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os-type: [fedora]
        os-version: ${{ fromJson(needs.get_fedora_releases.outputs.stable) }}
    container: ${{ matrix.os-type }}:${{ matrix.os-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get package name and version
        id: package-version
        uses: astrorama/actions/elements-project@v3.4
      - name: Install dependencies
        uses: astrorama/actions/setup-dependencies@v3.7
        with:
          dependency-list: .github/workflows/dependencies.txt
      - name: Build
        id: build
        uses: astrorama/actions/elements-build-rpm@v3.4
      - name: Upload RPM to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os-type }}${{ matrix.os-version }}
          path: ${{ steps.build.outputs.rpm-dir }}/*.rpm
          retention-days: 1
      - name: Upload RPM to repository
        if: ${{ github.repository_owner == 'astrorama' }}
        uses: astrorama/actions/upload-rpm@v3.4
        env:
          REPOSITORY_USER: ${{ secrets.REPOSITORY_USER }}
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
          REPOSITORY_KEY: ${{ secrets.REPOSITORY_KEY }}
        with:
          rpm-dir: ${{ steps.build.outputs.rpm-dir }}
          srpm-dir: ${{ steps.build.outputs.srpm-dir }}

#############
# Run tests #
#############
  litmus-test:
    if: ${{ always() }}
    needs: [ build, get_fedora_releases ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-type: [fedora]
        os-version: ${{ fromJson(needs.get_fedora_releases.outputs.stable) }}
    container: ${{ matrix.os-type }}:${{ matrix.os-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: astrorama/actions/setup-dependencies@v3.7
        with:
          dependency-list: .github/workflows/test-dependencies.txt
      - name: Download RPM
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os-type }}${{ matrix.os-version }}
      - name: Install SourceXtractor++
        run: yum install -y SourceXtractorPlusPlus*.x86_64.rpm
      - name: Run tests
        run: ./.github/workflows/run-litmus.sh
      - name: Upload reports and logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os-type }}${{ matrix.os-version }}-test-results
          path: /tmp/sourcex/
          retention-days: 5

